version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_sports
    restart: always
    env_file: app/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./app/models/schema.sql:/docker-entrypoint-initdb.d/schema.sql



volumes:
  mysql-data:
